### ISSUE TITLE
This header declaration is not working in the Carbon Calculator's lambda code

### ISSUE THREAD

**Issue by jackrwoods** [OSU-Sustainability-Office/lambda-common-layer#6]
https://github.com/OSU-Sustainability-Office/lambda-common-layer/blob/8f31347e77e0a133103158225d435d53db211109/dependencies/nodejs/response.js#L10

**Comment by broha22** [comment]
AWS SAM seems to overwrite these headers. I should remove them as they don't do anything. To work around the CORS issue use the sam_express.js file in the energy dashboard lambda branch or turn off cors checks in the browser.
